/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BussinesModelLayer.Farmacia;
import BussinesModelLayer.Producto;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class frmNProducto extends javax.swing.JDialog {

    private int idProducto = 0;//variable a nivel de clase **
    private Producto producto = new Producto();//inicializar el objeto vacio**
    private int tablaIdFarmClass[];

    /**
     * Creates new form frmNProducto
     */
    public frmNProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //crear constructor para poder llamar esta clase a la clase frmProductos atraves de una instancia que esta en el metodo btnNuevoActionPerformed, esta en la clase frmProductos
    public frmNProducto() {
        initComponents();//mandar a llamar los componentes
        Farmacia farm = new Farmacia();
        DefaultTableModel res = farm.GetAllModel();
        int NumFilas = res.getRowCount();
        int tablaIdFarm[];
        tablaIdFarm = new int[NumFilas];
        String tablaNombreFarm[];
        tablaNombreFarm = new String[NumFilas];
        int indexSelected = 0;
        for (int i = 0; i < NumFilas; i++) {
            tablaIdFarm[i] = (int) res.getValueAt(i, 0);
            tablaNombreFarm[i] = (String) res.getValueAt(i, 1);
            comboBoxIdFarmacia.addItem(tablaNombreFarm[i]);
        }
        this.tablaIdFarmClass = new int[NumFilas];
        this.tablaIdFarmClass = tablaIdFarm;
    }

    public frmNProducto(int idProducto) {//Crear otro constructor, el cual sera llamado cuando el boton de modificar sea presionado, entonces nos vamos ahora al btnModificarActionPerformed que esta en la clase frmProductos**
        initComponents();
        this.idProducto = idProducto;//se le pone la unica propiedad que es idProducto pero es la unica propiedad que ocupa para poder llamar al metodo GetById() y este metodo lo que hace es poblar las otras propiedades con la informacion de la base de datos
        producto.setIdProducto(idProducto);
        producto.GetById();//recuerda que este metodo lo que hacia era consultar en base de datos y llenar las mismas propiedades de este objeto de la misma clase
        txtNombre.setText(producto.getNombre());
        txtCaducidad.setText(producto.getCaducidad());
        txtStock.setText("" + producto.getStock());
        txtFarmacia.setText("" + producto.getIdFarmacia());
        Farmacia farm = new Farmacia();
        DefaultTableModel res = farm.GetAllModel();
        int NumFilas = res.getRowCount();
        int tablaIdFarm[];
        tablaIdFarm = new int[NumFilas];
        String tablaNombreFarm[];
        tablaNombreFarm = new String[NumFilas];
        int indexSelected = 0;
        for (int i = 0; i < NumFilas; i++) {
            tablaIdFarm[i] = (int) res.getValueAt(i, 0);
            tablaNombreFarm[i] = (String) res.getValueAt(i, 1);
            comboBoxIdFarmacia.addItem(tablaNombreFarm[i]);
            if (tablaIdFarm[i] == producto.getIdFarmacia()) {
                indexSelected = i;
            }

        }
        comboBoxIdFarmacia.setSelectedIndex(indexSelected);
        this.tablaIdFarmClass = new int[NumFilas];
        this.tablaIdFarmClass = tablaIdFarm;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtFarmacia = new javax.swing.JTextField();
        txtCaducidad = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        comboBoxIdFarmacia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Caducidad:");

        jLabel3.setText("Stock:");

        jLabel4.setText("idFarmacia:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnOk.setText("Guardar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFarmacia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxIdFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtCaducidad))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOk)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxIdFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();//cierra el dialogo
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if (producto.getIdProducto() > 0) {//osea si hay un Id es porque es Modificar
            producto.setNombre(txtNombre.getText());
            producto.setCaducidad(txtCaducidad.getText());
            producto.setStock(Integer.parseInt(txtStock.getText()));
            //producto.setIdFarmacia(Integer.parseInt(txtFarmacia.getText()));
            int idFarm = this.tablaIdFarmClass[(int) comboBoxIdFarmacia.getSelectedIndex()];
            producto.setIdFarmacia(idFarm);
            producto.setActivo(1);
            if (producto.Update()) {
                JOptionPane.showMessageDialog(null, "Producto actualizado correctamente");
                this.dispose();//cerramos
            }

        } else {// en caso de que no haiga Id es porque es agregar
            //Recordemos que nuestro paquete de negocios en la clase Producto hay un metodo de agregar (Add) que regresa un boolean osea si es mayor o igual a 1 es true menor de 1 es false, entonces hacemos lo siguiente:
            int idFarm = this.tablaIdFarmClass[(int) comboBoxIdFarmacia.getSelectedIndex()];
            if (new Producto(0,//le pasamos los parametros de la clase Producto por medio de parentesis
                    txtNombre.getText(),
                    txtCaducidad.getText(),//En esta parte se convirtio el tipo Date de la variable caducidad a String osea DATE to String
                    Integer.parseInt(txtStock.getText()),
                    //Integer.parseInt(txtFarmacia.getText()),
                    idFarm,
                    1).Add()) {
                JOptionPane.showMessageDialog(null, "Producto agregado correctamente");
                this.dispose();//cerramos el formulario despues de haber agrgado el producto; Entonces esto es lo que haria el codigo cuando se manda a llamar, entonces en el boton de Nuevo que estan en la interfaz de la clase frmProductos se va a mandar a llamar esta clase a traves de una instancia que va a estar en la clase de frmProductos en en btnNuevoActionPerformed
            }
        }

    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNProducto dialog = new frmNProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> comboBoxIdFarmacia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCaducidad;
    private javax.swing.JTextField txtFarmacia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
